### ISSUE TITLE
update jna and jna-platform version

### ISSUE THREAD

**Issue by EddyZhou97** [JetBrains/pty4j#100]
please update the jna and jna-platform version to latest version! It conflict with oshi 
![image](https://user-images.githubusercontent.com/36226819/108954985-6cfc7600-76a8-11eb-98cb-2bfde0f7dd5a.png)

**Comment by segrey** [comment]
@EddyZhou97 Just update pty4j from 0.8.6 to 0.11.4 (latest version as of now) - it depends on jna 5.6.0.
