### ISSUE TITLE
ppc64le binaries out of date

### ISSUE THREAD

**Issue by shawnanastasio** [JetBrains/pty4j#103]
It seems the linux/ppc64le binaries haven't been rebuilt in a while and as a result pty4j no longer functions on the platform:
```
2021-05-14 13:25:43,008 [ 151904]  ERROR - plication.impl.ApplicationImpl - Error looking up function 'set_window_size': /home/shawnanastasio/Downloads/clion-2020.2.1/lib/pty4j-native/linux/ppc64le/libpty.so: undefined symbol: set_window_size 
java.lang.UnsatisfiedLinkError: Error looking up function 'set_window_size': /home/shawnanastasio/Downloads/clion-2020.2.1/lib/pty4j-native/linux/ppc64le/libpty.so: undefined symbol: set_window_size
```

**Comment by shawnanastasio** [comment]
I have just built the binary locally and confirmed that it works as expected. Let me know if you would like me to submit a PR with my build of the binary.

**Comment by segrey** [comment]
@shawnanastasio Thanks for reporting. It should be fixed by https://github.com/JetBrains/pty4j/commit/0ace55a2e0f5ac9068e65aaf3a24ca9bb7666d2a.
