### ISSUE TITLE
Publish pty4j artifacts to Maven Central

### ISSUE THREAD

**Issue by chabala** [JetBrains/pty4j#105]
Issue #34 asked for pty4j to be published to Maven Central to allow others to use it more easily. Instead it was eventually published to Bintray, but not propagated to Central from there.

Bintray has since ceased operations and is now read only. Newer pty4j artifacts are [currently published to a JetBrains repository](https://github.com/JetBrains/pty4j/issues/34#issuecomment-851216993), but not Central.

Please publish to Maven Central.

**Comment by electricalen** [comment]
This is a major problem.  Is this project abandoned?

**Comment by lread** [comment]
I see something up on maven! 
https://mvnrepository.com/artifact/org.jetbrains.pty4j/pty4j

**Comment by chabala** [comment]
Looks like the required dependency `purejavacomm-0.0.11.1` is still not in Central.

**Comment by lread** [comment]
Oh probably still in progress, then! Good to see some movement!

**Comment by satsen** [comment]
When is JetBrains' purejavacomm getting published on maven? @segrey @DmPanov
The fact that pty4j is on maven is useless if that dependency isn't

**Comment by ajs1998** [comment]
This is still not fixed nearly 6 months later

**Comment by chabala** [comment]
> This is still not fixed nearly 6 months later

That's a bit generous, #34 was opened in 2016.

**Comment by Xiaobaishushu25** [comment]
This is still not fixed in 2023...  if you use maven，this is a  workaround：
```
<repositories>
    <repository>
        <id>jetbrains-repo</id>
        <url>https://packages.jetbrains.team/maven/p/ij/intellij-dependencies</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>org.jetbrains.pty4j</groupId>
        <artifactId>pty4j</artifactId> 
        <version>your-version</version> <!-- Specify the version you need -->
    </dependency>
</dependencies>

```

**Comment by sureshg** [comment]
This library is very useful and would be great if maintainers can fix the dependency issue by publishing `purejavacomm` to central.

**Comment by segrey** [comment]
Since pty4j 0.13.0, there is no longer dependency on `purejavacomm`.
https://search.maven.org/artifact/org.jetbrains.pty4j/pty4j/0.13.0/jar
