### ISSUE TITLE
Performance issues when initiating a new PTY on systems with high FD limits

### ISSUE THREAD

**Issue by rphsoftware** [JetBrains/pty4j#125]
When running on a system with a very high file descriptor limit, the library will take extreme amounts of time to initialize a new PTY properly. The culprit appears to be the following block of code: https://github.com/JetBrains/pty4j/blob/7bcaeb674bceb5e990914cec052b5c55f778fd9b/native/exec_pty.c#L125-L131 

A better solution on machines with the `/proc` filesystem available would be to perhaps try only closing file descriptors that are actually open?

**Comment by kprintf** [comment]
Related to PR https://github.com/JetBrains/pty4j/pull/124

**Comment by segrey** [comment]
Thank you for reporting and sorry for the delay. Should be fixed by https://github.com/JetBrains/pty4j/commit/04685d870fd09371fe8580f664be5aea41de5b2c and available since pty4j version 0.12.27.
