### ISSUE TITLE
maven&Java1.8

### ISSUE THREAD

**Issue by GSW-11** [JetBrains/pty4j#141]
My program is maven project, Java version is 1.8,can i use your program?

**Comment by segrey** [comment]
No, Java 11 is required (https://github.com/JetBrains/pty4j/blob/master/build.gradle#L57-L58)
Though you can build pty4j compatible with Java 1.8 manually from https://github.com/JetBrains/pty4j/tree/1.8

**Comment by GSW-11** [comment]
> No, Java 11 is required (https://github.com/JetBrains/pty4j/blob/master/build.gradle#L57-L58) Though you can build pty4j compatible with Java 1.8 manually from https://github.com/JetBrains/pty4j/tree/1.8

Alright,thank you for your reply.
