### ISSUE TITLE
Java 8 - pty4j - 1.8 branch

### ISSUE THREAD

**Issue by aalku** [JetBrains/pty4j#144]
I would like to have a Java 8 jar in Maven. I found your 1.8 branch and it works nicely but not having that release in Maven public repositories is giving me a hard time. I know close to nothing about public repositories and I'm not sure I should publish your software or what's the best and respectful way to do it.

I'm not even sure you are not publishing it because the version collides, the jdk8 and the jdk11 versions would have the same jar name. If you publish it you only would need to add a classifier or include the java version in the version number or something.

```
diff --git a/build.gradle b/build.gradle
index 7c423e3..f0602a1 100644
--- a/build.gradle
+++ b/build.gradle
@@ -139,6 +139,9 @@
       from components.java
       group rootProject.group
       artifactId archivesBaseName
+      artifact jar {
+        classifier 'jdk8'
+      }
       artifact sourcesZip
       artifact javadocJar {
         classifier 'javadoc'
@@ -173,7 +176,7 @@
         scm {
           connection = 'scm:git:git@github.com:JetBrains/pty4j.git'
           developerConnection = 'scm:git:ssh:github.com/JetBrains/pty4j.git'
-          url = 'https://github.com/JetBrains/pty4j'
+          url = 'https://github.com/JetBrains/pty4j/tree/1.8'
         }
       }
     }
```

With this tiny change I managed to build and use `pty4j-0.12.10-jdk8.jar` and it is perfect the only problem is that I wanted to distribute my project in a Spring Boot "thin jar" and it looks for the dependencies in maven repositories.

If you won't publish it I might do it myself somehow.

I love your project and I'm using it for my own Open Source project. I made a tunnelled ssh access with pty4j. Thanks a lot for any help or hint you can give!

**Comment by segrey** [comment]
Thanks, done
https://central.sonatype.com/artifact/org.jetbrains.pty4j/pty4j/0.12.10-jdk8/
https://repo1.maven.org/maven2/org/jetbrains/pty4j/pty4j/0.12.10-jdk8/
