### ISSUE TITLE
100% CPU when the _SC_OPEN_MAX is a big number

### ISSUE THREAD

**Issue by whywhy36** [JetBrains/pty4j#147]
We observed that it took very long time to open a JetBrains terminal in the new Amazon AL2023 VM. The CPU usage is 100% for process `PtyProcess Reap` (the full name of  that thread is `PtyProcess Reaper for [/bin/bash, --rcfile, /home/owner/.cache/JetBrains/RemoteDev/dist/ideaIU-2022.3.2/plugins/terminal/jediterm-bash.in, -i]`). 

`strace -p PID` indicates that JNA call was trying to close a huge range of FDs, which should be defined in [exe_pty.c](https://github.com/JetBrains/pty4j/blob/master/native/exec_pty.c#L124). If `_SC_OPEN_MAX` holds a big value, the loop would degrade the performance. 

The similar issue has been reported in other projects, such as 
- https://github.com/netdata/netdata/issues/14177
- https://bugzilla.redhat.com/show_bug.cgi?id=1537564

Wondering should we apply a similar patch as https://github.com/netdata/netdata/pull/14213 to the impacted codes.

**Comment by whywhy36** [comment]
The issue should also be fixed by PR https://github.com/JetBrains/pty4j/pull/124

**Comment by morgwai** [comment]
For Linux users affected by this problem and looking for a workaround:
Decreasing the limits of maximum open files mitigates the problem. See [this stackExchange post](https://unix.stackexchange.com/a/145025/271042) explaining how to set global and per process limits.

**Comment by segrey** [comment]
Thank you for reporting and sorry for the delay. Should be fixed by 04685d870fd09371fe8580f664be5aea41de5b2c and available since pty4j version 0.12.27.
