### ISSUE TITLE
Question - where is the source of org.jetbrains.pty4j:purejavacomm ?

### ISSUE THREAD

**Issue by PavelTurk** [JetBrains/pty4j#150]
From readme:

> This library depends on JTermios, part of the PureJavaComm library found at https://github.com/nyholku/purejavacomm. Pty4j depends on the forked version of PureJavaComm ([org.jetbrains.pty4j:purejavacomm](https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/org/jetbrains/pty4j/purejavacomm/)).

Could anyone say where it is possible to get the source of `forked version of PureJavaComm`?

**Comment by segrey** [comment]
Please see https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/org/jetbrains/pty4j/purejavacomm/0.0.11.1/

**Comment by segrey** [comment]
@PavelTurk No, unfortunately, there is no repo url to fetch the full project for building.
