### ISSUE TITLE
Use SLF4J instead of Log4J

### ISSUE THREAD

**Issue by rhwood** [JetBrains/pty4j#2]
I am using pty4j in a project that uses java.util.logging (JUL) instead of Log4J (and have no option to change that). If pty4j could use SLF4J instead of Log4J, I could eliminate an entire logging layer (and library) from this project.

Using SLF4J would allow projects that use JUL, LogBack, or no logging at all to use pty4j without having to implement and manage Log4J.

**Comment by yole** [comment]
Fixed with #116
