### ISSUE TITLE
Package native libraries into jar

### ISSUE THREAD

**Issue by sevenever** [JetBrains/pty4j#33]
`
Can you package the native libraries into the pty4j.jar file, so that it can be more easy to deploy.
I did a prototype that works on my OSX, I need to use lipo from Xcode to package x86 and x86_64 version of libpty.dylib into a multiarch library because looks like jna-platform [require a multiarch library](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Platform.java#L261) if you want package it into jar file.

diff --git a/src/com/pty4j/unix/PtyHelpers.java b/src/com/pty4j/unix/PtyHelpers.java
index 9d85fd6..cb10583 100644
--- a/src/com/pty4j/unix/PtyHelpers.java
+++ b/src/com/pty4j/unix/PtyHelpers.java
@@ -221,9 +221,7 @@ public class PtyHelpers {

   static {
     try {
-      File lib = PtyUtil.resolveNativeLibrary();
-
-      myPtyExecutor = new NativePtyExecutor(lib.getAbsolutePath());
+      myPtyExecutor = new NativePtyExecutor("pty");
     }
     catch (Exception e) {
       LOG.error("Can't load native pty executor library", e);
`

**Comment by bk1te** [comment]
+1
Can`t make pty4j to load native lib with spring-boot application started from JAR.
it fails at 
java.lang.IllegalArgumentException: URI is not hierarchical
       getJarContainingFolderPath(PtyUtil.java:42)

**Comment by segrey** [comment]
Native binaries are bundled into jar since 0.7.9 version. See https://bintray.com/jetbrains/pty4j/org.jetbrains.pty4j%3Apty4j.
