### ISSUE TITLE
publish to maven central ?

### ISSUE THREAD

**Issue by snimavat** [JetBrains/pty4j#34]
I dont see pty4j is published to maven central. Can we plz do it, so it can be used easily with maven/gradle etc

**Comment by czm4514** [comment]
can you use pty4j successfully?

**Comment by GaillardTheo** [comment]
You can use jitpack to directly download pty4j from GitHub:

```
repositories
{
	mavenCentral()
	maven
	{
		url "https://jitpack.io"
	}
}

dependencies
{
	compile "com.github.purejavacomm:purejavacomm:1.0.1.RELEASE"
	compile "com.github.traff:pty4j:master"
}

```

**Comment by sirolf2009** [comment]
It's been 2 years now. Is this happening or not? If not, would you mind if I publish it under my account?

**Comment by traff** [comment]
Hi! Actually, it has already happened: https://bintray.com/jetbrains/pty4j

**Comment by chabala** [comment]
Can this please be reopened? Bintray is not central, and it is going away. No artifacts have been published to central: https://search.maven.org/search?q=g:org.jetbrains*%20a:pty4j

**Comment by chabala** [comment]
At a minimum, the readme should be updated to reflect this. But please publish to Central.

**Comment by segrey** [comment]
@chabala We're considering publishing to Maven Central. This issue is old. Could you please file a new one?
