### ISSUE TITLE
Android is unsupported

### ISSUE THREAD

**Issue by oldosfan** [JetBrains/pty4j#75]
When running pty4j from an android project, it throws: 
` Caused by: java.lang.RuntimeException: Pty4J has no support for OS Linux
        at com.pty4j.unix.PtyHelpers.<clinit>(PtyHelpers.java:218)`

It seems to be caused by line 218 and 211 of PtyHelpers.java, in which line 211 calls `Platform.isLinux()` which returns false by default on android, due to android not being considered a Linux platform, which can be traced back to line 147 of Platform.java, then line 74:
`if ("dalvik".equals(System.getProperty("java.vm.name").toLowerCase())) {`, which sets `osType` to   `ANDROID` if the application is running in Dalvik or ART.

**Comment by segrey** [comment]
Don't have Android environment to check. @oldosfan Could you please describe your case for using pty4j on Android?
If replacing `Platform.isLinux()` with `Platform.isLinux() || Platform.isAndroid()` in com.pty4j.unix.PtyHelpers works for you, feel free to open a PR.
