### ISSUE TITLE
Issue in `pty.waitFor() ` 

### ISSUE THREAD

**Issue by Xarrow** [JetBrains/pty4j#87]
Hi, I am not sure whether `process.waitFor()` in a web application is necessary.  

In `Pty4j` official example, it shows `wait until the PTY child process terminates....` This code maybe only works in a none web application, it will exit after executing ，so they need to block the thread for input/output action. But in a web application, it is self blocked, so I am not sure whether `process.waitFor()` in a web application is necessary.

**Comment by segrey** [comment]
This is a basic example and it doesn't cover all possible usages. The idea of the example is to show that `PtyProcess` behaves like a regular `java.lang.Process`. If you don't need to wait until process is terminated, then don't use `process.waitFor()` which has the same contract as [java.lang.Process#waitFor()](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor--).
