### ISSUE TITLE
Support armv7

### ISSUE THREAD

**Issue by maggu2810** [JetBrains/pty4j#93]
The identical problem as already reported for aarch64 [Support aarch64](https://github.com/JetBrains/pty4j/issues/82) also exists for the Raspberry Pi 4 running the currently official 32 bit Raspberry Pi OS.

It would be great if there will be also a library shipped that works with ARMv7.

The instructions to compile the shared library works.
Currently the library needs to be copied to the x86 directory to get it used.

**Comment by AzazeII** [comment]
I would also highly appreciate if this library would work with ARMv7 out of the box, without compiling native code by hands

**Comment by segrey** [comment]
Thanks for reporting. Fixed by https://github.com/JetBrains/pty4j/commit/1fd5e571149076b55588e9c870758f8bc993e69d
